[package]
name = "program-scraping"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
curl = "0.4.44"
encoding = "0.2.33"
regex = "1.10.2"
